### ISSUE TITLE
Latest release tag doesn't point to the correct commit

### ISSUE THREAD

**Issue by nickbeth** [ItzNotABug/DocumentFileCompat#2]
Hey there.
I'm opening this issue as we're planning to use this library for [Skyline Emulator](https://github.com/skyline-emu/skyline). I figured I'd be writing essentially the same code, so it would be pretty stubborn of me to do the work again.

As per #1, some commits were added after tag [0.8](https://github.com/ItzNotABug/DocumentFileCompat/tree/0.8), but the tag was not updated accordingly.
#1 says the following:
> Completed via https://github.com/ItzNotABug/DocumentFileCompat/commit/f7df1334410976187ca43cf9ad8f19f015447c3b.
 The new artifact has the same api & has the same published version (0.8)

but the current 0.8 tag makes it confusing when looking at the repo. Is the new package published on Maven Central? And could you update tag 0.8 to point to the correct commit?

**Comment by ItzNotABug** [comment]
Hi there,
The only change was changing the artifact id from `documentfile_compat` to `dfc`.
So it made sense to upload the new artifact on `Maven Central` with same version (0.8).

**Comment by ItzNotABug** [comment]
You can simply use the `0.91` version which fixes a bug and already has the new artifcat-id with correct commit.
```groovy
implementation "com.lazygeniouz:dfc:0.91"
```
